# Generated by Django 5.1.1 on 2024-10-07 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='物品类别')),
            ],
            options={
                'verbose_name': '物品类别',
                'verbose_name_plural': '物品类别',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='物品名称')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('is_consumable', models.BooleanField(default=False, verbose_name='是否消耗品')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='价格')),
                ('image', models.ImageField(blank=True, upload_to='items/', verbose_name='图片')),
                ('overdue', models.DateField(blank=True, verbose_name='过期时间')),
                ('link', models.URLField(blank=True, verbose_name='链接')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemcategory', verbose_name='物品类别')),
            ],
            options={
                'verbose_name': '物品',
                'verbose_name_plural': '物品',
                'ordering': ['-create_time'],
            },
        ),
    ]
