# Generated by Django 5.1.1 on 2024-10-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='物品状态')),
            ],
            options={
                'verbose_name': '物品状态',
                'verbose_name_plural': '物品状态',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemstatus', verbose_name='物品状态'),
        ),
    ]
