# Generated by Django 5.1.1 on 2024-10-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_itemstatus_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='overdue',
            field=models.DateField(blank=True, null=True, verbose_name='过期时间'),
        ),
    ]
